name: wazuh

include:
  - ${WAZUH_DOCKER_GIT}/single-node/docker-compose.yml
  - ../wazuh-agent/docker-compose.yml
  - ../testserver/docker-compose.yml

services:
  wazuh.idmefv2:
    build:
      context: "containers/wazuh-idmefv2"
    ports:
      - 5678:5678/tcp
    volumes:
      - type: "volume"
        source: "wazuh_logs"
        target: "/var/ossec/logs"
      - type: "bind"
        source: "${IDMEFV2_CONNECTORS_GIT}"
        target: "/idmefv2-connectors"
#    entrypoint: "/entrypoint-debug.sh"
    entrypoint: "/entrypoint.sh"
